logo:
header: "Behzad Rahmani"
title: Behzad Rahmani
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Behzad Rahmani 
permalink: ":title/"
baseurl: "https://behzadrahmani.github.io" # the subpath of your site, e.g. /blog
domain: "behzadrahmani.github.io" # the base hostname for your site, e.g. example.com
url: "https://behzadrahmani.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Author settings
author-pic: Profile.png # your photo
author-name: Behzad Rahmani # your name
about-author: | # about author
  - Senior architect with over 15 years of experience in developing conceptual plans for residential and commercial buildings and landscape projects.
  <br>
  - Worked with over 700 clients to create personal spaces that meet their needs.
email: rbehutm@gmail.com # your email
phone: Available on Request # your phone number
website: https://behzadrahmani.github.io # your website


# Social link
email_url:     mailto:rbehutm@gmail.com
twitter_url:   ""
instagram_url: ""
reddit_url:    ""
linkedin_url:  "https://www.linkedin.com/in/behzad-rahmani-architect/"


# Paginate
paginate: 24
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll
  - jekyll-paginate
  - jekyll-sitemap
  - faraday-retry

include: [_pages]

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - README.md